Update release target and add git tag check
Signed-off-by: Joachim Nilsson <troglobit@gmail.com>

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -5,22 +5,45 @@ mcjoin_CFLAGS     = -W -Wall -Wextra -std=gnu99
 doc_DATA          = README.md LICENSE
 EXTRA_DIST        = README.md LICENSE ChangeLog.md
 
+# lintian --profile debian -i -I --show-overrides ../$PKG.changes
 package:
 	dpkg-buildpackage -uc -us -B
 
-## Target to run when building a release
-release: dist package
+## Generate MD5 checksum file
+MD5 = md5sum
+md5-dist:
 	@for file in $(DIST_ARCHIVES); do	\
-		md5sum $$file > ../$$file.md5;	\
+		$(MD5) $$file > ../$$file.md5;	\
 	done
+
+## Check if tagged in git
+release-hook:
+	if [ ! `git tag | grep $(PACKAGE_VERSION)` ]; then				\
+		echo;									\
+		printf "\e[1m\e[41mCannot find release tag $(PACKAGE_VERSION)\e[0m\n";	\
+		printf "\e[1m\e[5mDo release anyway?\e[0m "; read yorn;			\
+		if [ "$$yorn" != "y" -a "$$yorn" != "Y" ]; then				\
+			printf "OK, aborting release.\n";				\
+			exit 1;								\
+		fi;									\
+		echo;									\
+	else										\
+		echo;									\
+		printf "\e[1m\e[42mFound GIT release tag $(PACKAGE_VERSION)\e[0m\n";	\
+		printf "\e[1m\e[44m>>Remember to push tags!\e[0m\n";			\
+		echo;									\
+	fi
+
+## Target to run when building a release
+release: release-hook distcheck package md5-dist
 	@mv $(DIST_ARCHIVES) ../
 	@echo
 	@echo "Resulting release files:"
 	@echo "================================================================="
 	@for file in $(DIST_ARCHIVES); do					\
-		printf "$$file    \tDistribution tarball\n";			\
-		printf "$$file.md5\t"; cat ../$$file.md5 | cut -f1 -d' ';	\
+		printf "%-32s Distribution tarball\n" $$file;			\
+		printf "%-32s " $$file.md5; cat ../$$file.md5 | cut -f1 -d' ';	\
 	done
-	@for file in `ls ../$(PACKAGE)_$(VERSION)-*`; do			\
-		printf "$$file    \tDebian/Ubuntu file\n";			\
+	@for file in `cd ..; ls $(PACKAGE)_$(VERSION)*`; do			\
+		printf "%-32s Debian/Ubuntu package\n" $$file;			\
 	done
